//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiz2EPub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wiz2EPub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap gifSample {
            get {
                object obj = ResourceManager.GetObject("gifSample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap jpegSample {
            get {
                object obj = ResourceManager.GetObject("jpegSample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] page {
            get {
                object obj = ResourceManager.GetObject("page", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pngSample {
            get {
                object obj = ResourceManager.GetObject("pngSample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*ж ·ејЏеђЌз§°пјљиЂЃз‰›ж ·ејЏ*/
        ////*ж ·ејЏдЅњиЂ…пјљOxenпј€иЂЃиЂЃиЂЃз‰›пј‰*/
        ////*ж ·ејЏз‰€жњ¬пјљ4.3*/
        ////*ж ·ејЏж—Ґжњџпјљ2012-06-09*/
        ///
        ////*в†“в†“иЂЃз‰›е­—дЅ“ж ·ејЏ2.2 2012-04-20в†“в†“*/
        ////*в†“в†“ж¬ўиїЋйќће•†дёљжЂ§дЅїз”ЁпјЊдЅ†иЇ·жіЁжЋ&quot;иЂЃз‰›е­—дЅ“ж ·ејЏ&quot;пј›е•†дёљдЅїз”ЁиЇ·дёЋиЂЃз‰›иЃ”зі»в†“в†“*/
        ///@font-face {
        ///	font-family:&quot;zw&quot;;
        ///	src:url(../fonts/zw.ttf),
        ///	url(res:///opt/sony/ebook/FONT/zw.ttf),
        ///	url(res:///Data/FONT/zw.ttf),
        ///	url(res:///opt/sony/ebook/FONT/tt0011m_.ttf),
        ///	url(res:///ebook/fonts/../../mnt/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
